Homework 2
pnatashap/python_learning pull request #3
Opened 2021-03-31 22:05 UTC by pnatashap

Помимо реализации фунции изменила проверки:
задание 1: Временный файл нельзя прочитать из нашей функции, если он открыт. Поэтому добавила его закрытие и удаление после теста. Там еще удалялся файл result.txt, у меня такого нет, поэтому закоментировала строку. Ну и валидацию email добавила в вызов, но ничего не меняет особо.
задание 2. исправила входной массив и ожидаемый ответ, чтобы выход не всегда был отсортирован в обратном порядке (а то можно не то немного сделать, а он не ругнется)
задание 3. не трогала, хотя у меня мозг пошел перебирать с начала массива, а не с конца, но поменять было не сложно.
задание 4. добавила еще хеш одной функции, а то по одной как-то ощущение, что недопроверили.
задание 5. не меняла, с ним все хорошо

2021-04-01 13:04 UTC, alpakhomov requested changes
Давай исправим 1 и 5 задания, остальное на твое усмотрение

2021-04-01 13:04 UTC, alpakhomov commented on Lecture_2_Collections_homework/hw5.py
> +    return result
Тут в целом все логично начинается, идея проверки кол-ва параметров верная, но потом становится слишком сложно.
Первый шаг - разобраться с пришедшими параметрами. Старт, стоп и степ будут не индексами, а элементами коллекции, значит надо просто найти их в ней (у коллекций есть метод index например)
После того как ты разобралась с пришедшими параметрами, можно просто воспользоваться стандартными слайсами питона

2021-04-01 18:18 UTC, pnatashap commented on Lecture_2_Collections_homework/hw1.py
> +        with open(report_name, "w+") as report_file:
сначала была мысль сделать имя отчета report_имя_файла, но потом поняла, что они могут пересечься и добавляла просто индекс, но так и осталось разделенным.
w+ поставила, чтобы файл отчищался сам, я же не один раз запускала, перетирались файлы

2021-04-01 18:20 UTC, pnatashap commented on Lecture_2_Collections_homework/hw1.py
> +            report_file.flush()
у меня слишком часто в жизни винда теряла кусок файла, поэтому я так всегда делаю

2021-04-02 20:29 UTC, pnatashap commented on Lecture_2_Collections_homework/hw3.py
> +    return True
нууу... так не честно

2021-04-02 20:47 UTC, pnatashap commented on Lecture_2_Collections_homework/hw5.py
> +    return result
упростила

2021-04-02 20:48 UTC, pnatashap commented on Lecture_2_Collections_homework/hw2.py
> +        freq.update({i: new_val})
классно упрощает, да

2021-04-02 20:48 UTC, pnatashap commented on Lecture_2_Collections_homework/hw1.py
> +                    break
fixed

2021-04-03 13:56 UTC, alpakhomov approved these changes
Все отлично

2021-04-05 08:34 UTC, merged